[package]
name = "product_surreal"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
surrealdb = "2.1.0"
tokio = { version = "1.41.1", features = ["full"] }
